import type { Metadata } from 'next';
import localFont from 'next/font/local';
import ReactQueryProvider from './utils/Providers/ReactQueryProvider';
import './globals.css';

const rubik = localFont({
  src: './fonts/Rubik.ttf',
  variable: '--font-rubik'
});
const rubikItalic = localFont({
  src: './fonts/RubikItalic.ttf',
  variable: '--font-rubik-italic'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${rubikItalic.variable}`}>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
