module.exports = {
  "react/require-default-props": "off",
  "react/prop-types": "off",
  "react/jsx-filename-extension": ["error", { extensions: [".tsx"] }],
  "react/function-component-definition": "off",
  "react/jsx-props-no-spreading": "off",
  "react/no-array-index-key": "off",
  "max-len": ["off"],
  "semi": ["error", "always"],
  "@typescript-eslint/semi": ["error", "always"],
  "quotes": ["error", "single"],
  "comma-dangle": ["error", "never"],
  "consistent-return": "off",
  "import/extensions": "off",
}